// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axxquqtgbfqrorpddnxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4eHF1cXRnYmZxcm9ycGRkbnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NzM3NDksImV4cCI6MjA3MjE0OTc0OX0.G1bEj3VV2cKsvrFiWMgGzELF1KrO4JVuICQZotQIB04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});